pipeline {
    agent any
    stages {
        stage('Ansible-Playbook Execution') {
            steps {
                script {
                    try {
                        // Copia los archivos de inventario y playbooks de aws-ansible a la instancia EC2
                        sshagent(credentials: ['Your_SSH_Credentials']) {
                            sh "scp -o StrictHostKeyChecking=no -r inventory playbook ubuntu@ec2-100-26-106-101.compute-1.amazonaws.com:/tmp/"
                        }
                        
                        // Ejecuta el playbook de Ansible en la instancia EC2
                        sshagent(credentials: ['Your_SSH_Credentials']) {
                            sh "ssh -o StrictHostKeyChecking=no ubuntu@ec2-100-26-106-101.compute-1.amazonaws.com 'cd /tmp/playbook && ansible-playbook -i /tmp/inventory/inventory.yml nginx_install.yml'"
                        }
                    } catch (Exception e) {
                        currentBuild.result = 'FAILURE'
                        error("Error during Ansible playbook execution: ${e.message}")
                    }
                }
            }
        }
    }
}
